### ISSUE TITLE
[General] Alvin Reyes, lead on Outercore Eng, needs access to Equinix Metal Billing

### ISSUE THREAD

**Issue by jimmylee** [protocol/netops#13]
### What is the goal?
We're going to be forecasting the cost of Estuary. @alvin-reyes will need access to heightened privileges to Equinix Metal to see billing, he already has access to Equinix Metal.
  
### Why do you need this?
@alvin-reyes already manages quite a bit of infrastructure for Estuary and other projects for Outercore Engineering. This just lets him do his job better and even help advise when services can be optimized.
  
### What else do we need to know?
Nothing, I'm doing this document as a formality.

**DRI:** myself
I'm available 24/7 in Slack, in both channels: Protocol Labs, and Filecoin Slack.

**Comment by coryschwartz** [comment]
Sent a billing account invite to @alvin-reyes' email. Will follow up in a DM.

**Comment by jimmylee** [comment]
Thanks @coryschwartz !!
