### ISSUE TITLE
[General] 1Pass Vault access for new labbers

### ISSUE THREAD

**Issue by placer14** [protocol/netops#17]
### What is the goal?
- Onboard new labbers into 1pass
  
### What else do we need to know?
The following labbers need access:
- Karol Kazlowski
- Loc Nguyen
- Po-chun "Birdy" Chang

to the following vaults:
- (PL) Shared  
- Infra team
  - [x] Karol Kazlowski
  - [x] Loc Nguyen
  - [x] Po-chun "Birdy" Chang

**DRI:** @placer14

**Comment by gmasgras** [comment]
Added to `Infra team`. I don't have admin on `(PL) Shared`

**Comment by placer14** [comment]
Looks like PL Shared should be done upon 1Pass setup. Closing as resolved. Thanks @gmasgras 🙏
