### ISSUE TITLE
[General] Hydra-Booster Provider-/Peer-Record Correlation

### ISSUE THREAD

**Issue by dennis-tra** [protocol/netops#21]
### What is the goal?

- Related [Slack thread](https://filecoinproject.slack.com/archives/C03CKEPVA1Y/p1663594871874599)
- Related [Notion page](https://pl-strflt.notion.site/Hydras-Reliability-and-Effectiveness-7aa5088070794bd795780b74533bd6b2)

We want to be able to do exploratory analyses on hydra-booster data (provider-records plus peer-records) which are running on PL's infrastructure - and perhaps set up an analysis pipeline that runs continuously (if a metric proves to be important). 

Things that we want to find out include, e.g., content churn and geographic content distribution. For the latter, we want to correlate provider- and peer-records by following the link CID->PeerID->Multi-Addresses->IP-Addresses->Country. We can get all necessary information from DynamoDB dumps (provider-records) and the in-memory peer store (peer-records).

Given the size of the data, it’s not feasible to do the analysis locally so I figured to do it solely on AWS. I already set up a pipeline for the provider-record data (DynamoDB->S3->Glue->Athena) which works fine. To get the peer-records into the equation I’ve also got some ideas but would love to discuss the architecture and interplay with someone more familiar than me.
  
### Why do you need this?

Given how central the role of Hydras has become, it is imperative to have better visibility into their performance and what guarantees can they provide. Insights about content churn and geographic distribution could guide DHT protocol adjustments.

### What else do we need to know?

I guess, my request can be satisfied with some consultancy to enable me to do the above myself if the team is short on capacity.

**DRI:** myself

**Comment by placer14** [comment]
Closing in preference for [a PLDW-specific issue](https://github.com/protocol/pldw/issues/154).
