### ISSUE TITLE
[AWS] Account for Cryptonet

### ISSUE THREAD

**Issue by jaeaster** [protocol/netops#29]
### Request Description
Cryptonet would like to have an AWS account set up and managed by us. This account would be used to run infrastructure for testnet/mainnet products/protocols. We also have a need for research and experimental projects.

### Desired Results/Outcome
We can run sensitive infrastructure in a resilient manner with isolation from other teams' infrastructure; our cloud usage is directly billable to PL.

**Comment by coryschwartz** [comment]
I've created teh cryptonet account, credentials passed in slack.
