### ISSUE TITLE
[AWS] Increase scaling group blowfish on mainnet-us-east-1-eks

### ISSUE THREAD

**Issue by placer14** [protocol/netops#30]
### Request Description
I need the scaling group's desired nodes to be increased by 1 so I can have headroom while doing maintenance on Sentinel. Maintenance involves a rolling update and there's no room in the group to schedule new pods to replace the old ones to-be-destroyed.

### Desired Results/Outcome
In AWS account: `759815798766`
On scaling group: [`eks-b0bde60d-3a22-c598-190c-f564870538f3`](https://us-east-1.console.aws.amazon.com/ec2/autoscaling/home?#AutoScalingGroups:id=eks-b0bde60d-3a22-c598-190c-f564870538f3)
Increase `Desired Size`: `15` -> `16`

**Comment by stongo** [comment]
scaled!
