### ISSUE TITLE
[General] Move OpsGenie integration to #netops-issues

### ISSUE THREAD

**Issue by placer14** [protocol/netops#31]
Could you please enable `/opsgenie alert` in #netops-issues?

**Comment by stongo** [comment]
Using a public Slack workspace seems to make this a little difficult.

1. `/genie help connect` seems to map to an opsgenie user, not an API token. To use a bot user, I need to also be able to login via gsuite. This will require involving Pathfinder. Mapping my own user to a slack bot isn't plausible for security implications.
2. non-admins in Slack may not be able to execute `/genie` commands in Slack. To confirm

**Comment by stongo** [comment]
when trying to login to opsgenie as infra-accounts@protocol.ai
![infra-accounts-opsgneie-login](https://user-images.githubusercontent.com/1449748/194684506-df8a0e7f-68b1-4176-9729-041369cf46e8.png)

**Comment by placer14** [comment]
@stongo It looks like the alerts are still going to the old channel as well. Could we move those too?

**Comment by stongo** [comment]
I disabled the old integration from PL Slack
Also tested the Filecoin Slack integration in #netops-issues and all is good.
Considering this done
