### ISSUE TITLE
[General] Add vmx to miner-3

### ISSUE THREAD

**Issue by vmx** [protocol/netops#7]
### What is the goal?

Having a user called `vmx` on the `miner-3` machine. The public key is at https://github.com/vmx.keys or any `worker-gpu-*` machine.
  
### Why do you need this?

I need a bigger machine than the worker-gpu one.
  
### What else do we need to know?

It would be really appreciate to have access by my tomorrow (CEST).

**DRI:** myself

**Comment by coryschwartz** [comment]
Thanks, @placer14

**Comment by coryschwartz** [comment]
@vmx I added your account to the miner nodes.

10.2.1.1
10.2.2.31
10.2.3.1

Let me know if you have trouble getting in!
