### ISSUE TITLE
[General] Need root/sudo permission on data-center machines for filecoin-crypto team

### ISSUE THREAD

**Issue by shawnrader** [protocol/netops#8]
### What is the goal?
I am setting up the following datacenter hosts to work as self-hosted runners to be used with testing piplelines on CircleCI and GitHub:
worker-cpu-2-1 (10.2.2.13)
worker-gpu-4 (10.2.2.27)
worker-gpu-7 (10.2.2.24)
miner-2 (10.2.2.31)

I need sudo access on the above machines in order to set them up as self hosted runners and fix various issues with the build and test process. We also have a team Grafana dashboard and I want to install prometheus agent on these hosts so we can monitor performance of them. I currently have an account on all four machines but only have sudo access only on miner-2 above but not the other three hosts. I need admin access on all four in order to set them up for testing.

  
### Why do you need this?
We are setting up long haul testing on the Filecoin Proofs library to tests sector sealing, performance regressions, and memory leaks.  The testing will be orchestrated using self-hosted runners agent with CircleCI.

  
### What else do we need to know?
shawnrader is my account name on these hosts and github.

**DRI:** myself

**Comment by shawnrader** [comment]
Ping on this request.  I would like to get Prometheus agent installed on all filecoin-crypto datacenter hosts so we can monitor them with Grafana, and install Github actions agent on some of them, but I cannot do either without admin.  Another option would be for Netops to provision the hosts so we can use them.

**Comment by ognots** [comment]
@coryschwartz can you get @shawnrader set up with Prometheus in the DC.
@shawnrader it's already installed and in grafana cloud as a data source

**Comment by coryschwartz** [comment]
oh! so you have an account that cannot sudo? I'll look into that.

**Comment by shawnrader** [comment]
Yeah I can only sudo on miner-2 for some reason.  Nemo may have manually added me on that machine.
For Grafana we also need nvidia GPU exporter installed (which requires sudo).  I have this installed on miner-2 and miner-3 but can't on the others.
The test I'm running requires ~1TB of disk space on a single partition, so usually I need to be able to cleanup tmp files left by other users or create folders on other partitions, which I can't do without sudo access.

**Comment by shawnrader** [comment]
Ping on this request.  My account still cannot sudo on the data center machines, except those which Nemo and vmx manually added me to.

**Comment by coryschwartz** [comment]
hey @shawnrader -- I think you should be good to know now. Looks like you were not in the right groups on some hosts.

**Comment by shawnrader** [comment]
Confirmed, thank you!
