### ISSUE TITLE
Fix lily logs in loki

### ISSUE THREAD

**Issue by frrist** [protocol/netops#9]
The json isn't being parsed correctly for all Sentinel Lily deployments in WGE cluster:

![Screen Shot 2022-09-06 at 17 18 43](https://user-images.githubusercontent.com/6546409/188943014-4c01d7e4-a02f-495c-99dc-d3591551d181.png)

**Comment by placer14** [comment]
Resolving this issue in https://github.com/filecoin-project/sentinel-infra/issues/332.
